# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
    - 'main'
    paths: 
    - 'input.yaml'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-push:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.10'
      - 
        name: Install Python Dependancies
        run: pip install pyyaml
      -
        name: Execute Python script
        id: python-script
        run: python python.py
      -
        name: Check Variables
        run: echo "Test +++++++++++++++> ${{steps.python-script.outputs.R_VERSION}}"
      -
        name: Update R version
        run: |
          sed -i -e "${{steps.python-script.outputs.R_VERSION}}" Dockerfile  
          sed -i -e "${{steps.python-script.outputs.R_VERSION}}" pkgr.yml
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: godasn.jfrog.io
          username: ${{ secrets.JF_USERNAME }}
          password: ${{ secrets.JF_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: godasn.jfrog.io/godasn/myimage:latest
